/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedOrganizationRouteImport } from './routes/_authed/_organization'
import { Route as AuthedOrganizationIndexRouteImport } from './routes/_authed/_organization/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedOrganizationRoute = AuthedOrganizationRouteImport.update({
  id: '/_organization',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationIndexRoute = AuthedOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrganizationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthedOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthedOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/_organization': typeof AuthedOrganizationRouteWithChildren
  '/_authed/_organization/': typeof AuthedOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/_organization'
    | '/_authed/_organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_organization': {
      id: '/_authed/_organization'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_organization/': {
      id: '/_authed/_organization/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedOrganizationIndexRouteImport
      parentRoute: typeof AuthedOrganizationRoute
    }
  }
}

interface AuthedOrganizationRouteChildren {
  AuthedOrganizationIndexRoute: typeof AuthedOrganizationIndexRoute
}

const AuthedOrganizationRouteChildren: AuthedOrganizationRouteChildren = {
  AuthedOrganizationIndexRoute: AuthedOrganizationIndexRoute,
}

const AuthedOrganizationRouteWithChildren =
  AuthedOrganizationRoute._addFileChildren(AuthedOrganizationRouteChildren)

interface AuthedRouteChildren {
  AuthedOrganizationRoute: typeof AuthedOrganizationRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrganizationRoute: AuthedOrganizationRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
