/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrganizationSetupRouteImport } from './routes/organization-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/_settings'
import { Route as AuthedOrganizationRouteImport } from './routes/_authed/_organization'
import { Route as AuthedOrganizationIndexRouteImport } from './routes/_authed/_organization/index'
import { Route as AuthedOrganizationWeb3FunctionsRouteImport } from './routes/_authed/_organization/web3-functions'
import { Route as AuthedOrganizationProfilesRouteImport } from './routes/_authed/_organization/profiles'
import { Route as AuthedOrganizationExecutablesRouteImport } from './routes/_authed/_organization/executables'
import { Route as AuthedOrganizationExecutablesIndexRouteImport } from './routes/_authed/_organization/executables.index'
import { Route as AuthedSettingsSettingsSettingsRouteImport } from './routes/_authed/_settings/settings/settings'
import { Route as AuthedSettingsSettingsApiKeysRouteImport } from './routes/_authed/_settings/settings/api-keys'
import { Route as AuthedOrganizationExecutablesExecutableIdRouteImport } from './routes/_authed/_organization/executables.$executableId'

const OrganizationSetupRoute = OrganizationSetupRouteImport.update({
  id: '/organization-setup',
  path: '/organization-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/_settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationRoute = AuthedOrganizationRouteImport.update({
  id: '/_organization',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationIndexRoute = AuthedOrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOrganizationRoute,
} as any)
const AuthedOrganizationWeb3FunctionsRoute =
  AuthedOrganizationWeb3FunctionsRouteImport.update({
    id: '/web3-functions',
    path: '/web3-functions',
    getParentRoute: () => AuthedOrganizationRoute,
  } as any)
const AuthedOrganizationProfilesRoute =
  AuthedOrganizationProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthedOrganizationRoute,
  } as any)
const AuthedOrganizationExecutablesRoute =
  AuthedOrganizationExecutablesRouteImport.update({
    id: '/executables',
    path: '/executables',
    getParentRoute: () => AuthedOrganizationRoute,
  } as any)
const AuthedOrganizationExecutablesIndexRoute =
  AuthedOrganizationExecutablesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedOrganizationExecutablesRoute,
  } as any)
const AuthedSettingsSettingsSettingsRoute =
  AuthedSettingsSettingsSettingsRouteImport.update({
    id: '/settings/settings',
    path: '/settings/settings',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsSettingsApiKeysRoute =
  AuthedSettingsSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedOrganizationExecutablesExecutableIdRoute =
  AuthedOrganizationExecutablesExecutableIdRouteImport.update({
    id: '/$executableId',
    path: '/$executableId',
    getParentRoute: () => AuthedOrganizationExecutablesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/organization-setup': typeof OrganizationSetupRoute
  '/executables': typeof AuthedOrganizationExecutablesRouteWithChildren
  '/profiles': typeof AuthedOrganizationProfilesRoute
  '/web3-functions': typeof AuthedOrganizationWeb3FunctionsRoute
  '/': typeof AuthedOrganizationIndexRoute
  '/executables/$executableId': typeof AuthedOrganizationExecutablesExecutableIdRoute
  '/settings/api-keys': typeof AuthedSettingsSettingsApiKeysRoute
  '/settings/settings': typeof AuthedSettingsSettingsSettingsRoute
  '/executables/': typeof AuthedOrganizationExecutablesIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/organization-setup': typeof OrganizationSetupRoute
  '/profiles': typeof AuthedOrganizationProfilesRoute
  '/web3-functions': typeof AuthedOrganizationWeb3FunctionsRoute
  '/': typeof AuthedOrganizationIndexRoute
  '/executables/$executableId': typeof AuthedOrganizationExecutablesExecutableIdRoute
  '/settings/api-keys': typeof AuthedSettingsSettingsApiKeysRoute
  '/settings/settings': typeof AuthedSettingsSettingsSettingsRoute
  '/executables': typeof AuthedOrganizationExecutablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/organization-setup': typeof OrganizationSetupRoute
  '/_authed/_organization': typeof AuthedOrganizationRouteWithChildren
  '/_authed/_settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/_organization/executables': typeof AuthedOrganizationExecutablesRouteWithChildren
  '/_authed/_organization/profiles': typeof AuthedOrganizationProfilesRoute
  '/_authed/_organization/web3-functions': typeof AuthedOrganizationWeb3FunctionsRoute
  '/_authed/_organization/': typeof AuthedOrganizationIndexRoute
  '/_authed/_organization/executables/$executableId': typeof AuthedOrganizationExecutablesExecutableIdRoute
  '/_authed/_settings/settings/api-keys': typeof AuthedSettingsSettingsApiKeysRoute
  '/_authed/_settings/settings/settings': typeof AuthedSettingsSettingsSettingsRoute
  '/_authed/_organization/executables/': typeof AuthedOrganizationExecutablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/home'
    | '/login'
    | '/organization-setup'
    | '/executables'
    | '/profiles'
    | '/web3-functions'
    | '/'
    | '/executables/$executableId'
    | '/settings/api-keys'
    | '/settings/settings'
    | '/executables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/login'
    | '/organization-setup'
    | '/profiles'
    | '/web3-functions'
    | '/'
    | '/executables/$executableId'
    | '/settings/api-keys'
    | '/settings/settings'
    | '/executables'
  id:
    | '__root__'
    | '/_authed'
    | '/home'
    | '/login'
    | '/organization-setup'
    | '/_authed/_organization'
    | '/_authed/_settings'
    | '/_authed/_organization/executables'
    | '/_authed/_organization/profiles'
    | '/_authed/_organization/web3-functions'
    | '/_authed/_organization/'
    | '/_authed/_organization/executables/$executableId'
    | '/_authed/_settings/settings/api-keys'
    | '/_authed/_settings/settings/settings'
    | '/_authed/_organization/executables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OrganizationSetupRoute: typeof OrganizationSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/organization-setup': {
      id: '/organization-setup'
      path: '/organization-setup'
      fullPath: '/organization-setup'
      preLoaderRoute: typeof OrganizationSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_settings': {
      id: '/_authed/_settings'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_organization': {
      id: '/_authed/_organization'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedOrganizationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_organization/': {
      id: '/_authed/_organization/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedOrganizationIndexRouteImport
      parentRoute: typeof AuthedOrganizationRoute
    }
    '/_authed/_organization/web3-functions': {
      id: '/_authed/_organization/web3-functions'
      path: '/web3-functions'
      fullPath: '/web3-functions'
      preLoaderRoute: typeof AuthedOrganizationWeb3FunctionsRouteImport
      parentRoute: typeof AuthedOrganizationRoute
    }
    '/_authed/_organization/profiles': {
      id: '/_authed/_organization/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthedOrganizationProfilesRouteImport
      parentRoute: typeof AuthedOrganizationRoute
    }
    '/_authed/_organization/executables': {
      id: '/_authed/_organization/executables'
      path: '/executables'
      fullPath: '/executables'
      preLoaderRoute: typeof AuthedOrganizationExecutablesRouteImport
      parentRoute: typeof AuthedOrganizationRoute
    }
    '/_authed/_organization/executables/': {
      id: '/_authed/_organization/executables/'
      path: '/'
      fullPath: '/executables/'
      preLoaderRoute: typeof AuthedOrganizationExecutablesIndexRouteImport
      parentRoute: typeof AuthedOrganizationExecutablesRoute
    }
    '/_authed/_settings/settings/settings': {
      id: '/_authed/_settings/settings/settings'
      path: '/settings/settings'
      fullPath: '/settings/settings'
      preLoaderRoute: typeof AuthedSettingsSettingsSettingsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/_settings/settings/api-keys': {
      id: '/_authed/_settings/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsSettingsApiKeysRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/_organization/executables/$executableId': {
      id: '/_authed/_organization/executables/$executableId'
      path: '/$executableId'
      fullPath: '/executables/$executableId'
      preLoaderRoute: typeof AuthedOrganizationExecutablesExecutableIdRouteImport
      parentRoute: typeof AuthedOrganizationExecutablesRoute
    }
  }
}

interface AuthedOrganizationExecutablesRouteChildren {
  AuthedOrganizationExecutablesExecutableIdRoute: typeof AuthedOrganizationExecutablesExecutableIdRoute
  AuthedOrganizationExecutablesIndexRoute: typeof AuthedOrganizationExecutablesIndexRoute
}

const AuthedOrganizationExecutablesRouteChildren: AuthedOrganizationExecutablesRouteChildren =
  {
    AuthedOrganizationExecutablesExecutableIdRoute:
      AuthedOrganizationExecutablesExecutableIdRoute,
    AuthedOrganizationExecutablesIndexRoute:
      AuthedOrganizationExecutablesIndexRoute,
  }

const AuthedOrganizationExecutablesRouteWithChildren =
  AuthedOrganizationExecutablesRoute._addFileChildren(
    AuthedOrganizationExecutablesRouteChildren,
  )

interface AuthedOrganizationRouteChildren {
  AuthedOrganizationExecutablesRoute: typeof AuthedOrganizationExecutablesRouteWithChildren
  AuthedOrganizationProfilesRoute: typeof AuthedOrganizationProfilesRoute
  AuthedOrganizationWeb3FunctionsRoute: typeof AuthedOrganizationWeb3FunctionsRoute
  AuthedOrganizationIndexRoute: typeof AuthedOrganizationIndexRoute
}

const AuthedOrganizationRouteChildren: AuthedOrganizationRouteChildren = {
  AuthedOrganizationExecutablesRoute:
    AuthedOrganizationExecutablesRouteWithChildren,
  AuthedOrganizationProfilesRoute: AuthedOrganizationProfilesRoute,
  AuthedOrganizationWeb3FunctionsRoute: AuthedOrganizationWeb3FunctionsRoute,
  AuthedOrganizationIndexRoute: AuthedOrganizationIndexRoute,
}

const AuthedOrganizationRouteWithChildren =
  AuthedOrganizationRoute._addFileChildren(AuthedOrganizationRouteChildren)

interface AuthedSettingsRouteChildren {
  AuthedSettingsSettingsApiKeysRoute: typeof AuthedSettingsSettingsApiKeysRoute
  AuthedSettingsSettingsSettingsRoute: typeof AuthedSettingsSettingsSettingsRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsSettingsApiKeysRoute: AuthedSettingsSettingsApiKeysRoute,
  AuthedSettingsSettingsSettingsRoute: AuthedSettingsSettingsSettingsRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedOrganizationRoute: typeof AuthedOrganizationRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedOrganizationRoute: AuthedOrganizationRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OrganizationSetupRoute: OrganizationSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
